# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='',
  serialized_pb=_b('\n\x0c\x63onfig.proto\"\xe6\x03\n\nExperiment\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x15\n\nnum_trials\x18\x02 \x01(\r:\x01\x31\x12\x16\n\x0bnum_workers\x18\x03 \x01(\r:\x01\x31\x12\x1a\n\x0btime_distro\x18\x04 \x01(\t:\x05\x63onst\x12\x1c\n\x0bresults_dir\x18\x05 \x01(\t:\x07results\x12\x15\n\x06method\x18\x06 \x01(\t:\x05slice\x12\x19\n\x0bnoisy_evals\x18\x07 \x01(\x08:\x04true\x12\x18\n\x0bnoise_scale\x18\x08 \x01(\x02:\x03\x30.1\x12\x19\n\x08reporter\x18\t \x01(\t:\x07\x64\x65\x66\x61ult\x12\x1d\n\x11initial_pool_size\x18\n \x01(\r:\x02\x32\x30\x12+\n\x08variable\x18\x0b \x03(\x0b\x32\x19.Experiment.ParameterSpec\x1a\xad\x01\n\rParameterSpec\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x33\n\x04type\x18\x02 \x01(\x0e\x32\x1e.Experiment.ParameterSpec.Type:\x05\x46LOAT\x12\x0e\n\x03\x64im\x18\x03 \x01(\r:\x01\x31\x12\x11\n\x03min\x18\x04 \x01(\x01:\x04-inf\x12\x10\n\x03max\x18\x05 \x01(\x01:\x03inf\"$\n\x04Type\x12\t\n\x05\x46LOAT\x10\x01\x12\x07\n\x03INT\x10\x02\x12\x08\n\x04\x45NUM\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_EXPERIMENT_PARAMETERSPEC_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Experiment.ParameterSpec.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENUM', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=467,
  serialized_end=503,
)
_sym_db.RegisterEnumDescriptor(_EXPERIMENT_PARAMETERSPEC_TYPE)


_EXPERIMENT_PARAMETERSPEC = _descriptor.Descriptor(
  name='ParameterSpec',
  full_name='Experiment.ParameterSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Experiment.ParameterSpec.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Experiment.ParameterSpec.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dim', full_name='Experiment.ParameterSpec.dim', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='Experiment.ParameterSpec.min', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=-1e10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='Experiment.ParameterSpec.max', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=1e10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPERIMENT_PARAMETERSPEC_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=503,
)

_EXPERIMENT = _descriptor.Descriptor(
  name='Experiment',
  full_name='Experiment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Experiment.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_trials', full_name='Experiment.num_trials', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_workers', full_name='Experiment.num_workers', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_distro', full_name='Experiment.time_distro', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("const").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='results_dir', full_name='Experiment.results_dir', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("results").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='Experiment.method', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("slice").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noisy_evals', full_name='Experiment.noisy_evals', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noise_scale', full_name='Experiment.noise_scale', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reporter', full_name='Experiment.reporter', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("default").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_pool_size', full_name='Experiment.initial_pool_size', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=20,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variable', full_name='Experiment.variable', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXPERIMENT_PARAMETERSPEC, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=503,
)

_EXPERIMENT_PARAMETERSPEC.fields_by_name['type'].enum_type = _EXPERIMENT_PARAMETERSPEC_TYPE
_EXPERIMENT_PARAMETERSPEC.containing_type = _EXPERIMENT
_EXPERIMENT_PARAMETERSPEC_TYPE.containing_type = _EXPERIMENT_PARAMETERSPEC
_EXPERIMENT.fields_by_name['variable'].message_type = _EXPERIMENT_PARAMETERSPEC
DESCRIPTOR.message_types_by_name['Experiment'] = _EXPERIMENT

Experiment = _reflection.GeneratedProtocolMessageType('Experiment', (_message.Message,), dict(

  ParameterSpec = _reflection.GeneratedProtocolMessageType('ParameterSpec', (_message.Message,), dict(
    DESCRIPTOR = _EXPERIMENT_PARAMETERSPEC,
    __module__ = 'config_pb2'
    # @@protoc_insertion_point(class_scope:Experiment.ParameterSpec)
    ))
  ,
  DESCRIPTOR = _EXPERIMENT,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:Experiment)
  ))
_sym_db.RegisterMessage(Experiment)
_sym_db.RegisterMessage(Experiment.ParameterSpec)


# @@protoc_insertion_point(module_scope)
